global using GoneDotNet.HeadsUp.Services;
global using Shiny;
global using System;
global using System.Collections.Generic;
global using Microsoft.Extensions.Logging;
global using Shiny.Extensions.DependencyInjection;
global using CommunityToolkit.Maui;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;