using System.ClientModel;
using Azure.AI.OpenAI;
using GoneDotNet.HeadsUp.Services.Impl;
using Microsoft.Extensions.AI;
using Shiny.SqliteDocumentDb;
using GameCategoryData = GoneDotNet.HeadsUp.Services.Impl.GameCategory;

namespace GoneDotNet.HeadsUp;


public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp
            .CreateBuilder()
            .UseMauiApp<App>()
            .UseMauiCommunityToolkit()
            .UseMauiCommunityToolkitMediaElement(false)
            .UseShinyShell(x => x.AddGeneratedMaps())
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            });
        
#if DEBUG
        builder.Logging.SetMinimumLevel(LogLevel.Trace);
        builder.Logging.AddDebug();
        builder.Logging.AddFilter("GoneDotNet.HeadsUp.Services.Impl.SensorAnswerDetector", LogLevel.Warning);
#endif
        var client = new AzureOpenAIClient(
            new Uri(Constants.AzureOpenAiEndpoint),
            new ApiKeyCredential(Constants.AzureOpenAiApiKey)
        );
        var chatClient = client.GetChatClient(Constants.AzureOpenAiModel).AsIChatClient();
        builder.Services.AddChatClient(chatClient).UseFunctionInvocation().UseLogging();

        builder.Services.AddSingleton(TimeProvider.System);
        builder.Services.AddSingleton(FileSystem.Current);
        builder.Services.AddSingleton(Connectivity.Current);
        builder.Services.AddSingleton<IVersionTracking>(VersionTracking.Default);
        builder.Services.AddDatabase();
        
        // this is source generated by Shiny.Extensions.DependencyInjection - simply add [Singleton], [Scoped], or [Transient] to your classes
        builder.Services.AddGeneratedServices();
        var app = builder.Build();
        
        return app;
    }
}